name: sccache install
description: Install sccache
inputs:
  key:
    required: true
    default: rust-cache-${{ runner.os }}-${{ runner.arch }}

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux' && runner.arch == 'X64'
      run: |
        echo "SCCACHE_ARCH=x86_64-unknown-linux-musl" >> $GITHUB_ENV
      shell: bash

    - if: runner.os == 'macOS' && runner.arch == 'X64'
      run: |
        echo "SCCACHE_ARCH=x86_64-apple-darwin" >> $GITHUB_ENV
      shell: bash

    - if: runner.os == 'macOS' && runner.arch == 'ARM64'
      run: |
        echo "SCCACHE_ARCH=aarch64-apple-darwin" >> $GITHUB_ENV
      shell: bash

    - if: runner.os == 'Linux' &&  runner.arch == 'ARM64'
      run: |
        echo "SCCACHE_ARCH=aarch64-unknown-linux-musl" >> $GITHUB_ENV
      shell: bash

    - name: Configure AWS Credentials
      id: aws-creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: 'us-west-2'
        role-to-assume: arn:aws:iam::083632199359:role/gha_oidc_risc0_cache_public_access
        output-credentials: true

    - env:
        SCCACHE_URL: https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION: v0.5.0
        SCCACHE_BUCKET: risc0-ci-cache
        SCCACHE_REGION: us-west-2
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-$SCCACHE_ARCH
        curl -L "$SCCACHE_URL/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mkdir -p $HOME/.local/bin
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash


    - uses: risc0/actions-cache@v1
        with:
          #endpoint: play.min.io # optional, default s3.amazonaws.com
          insecure: false # optional, use http instead of https. default false
          accessKey: ${{ steps.aws-creds.outputs.aws-access-key-id }} # required
          secretKey: ${{ steps.aws-creds.outputs.aws-secret-access-key }} # required
          sessionToken: ${{ steps.creds.outputs.aws-session-token }} # optional
          bucket: risc0-ci-cache # required
          use-fallback: true # optional, use github actions cache fallback, default true

#    - if: runner.os != 'macOS'
#      name: Cache rust target + HAL_CACHE
#      uses: risc0/rust-cache@v2.5.1
#      id: rust-cache
#      with:
#        key: ${{ inputs.key }}
#        # TODO: this path will not work on windows.
#        cache-directories: ~/.cache/risc0

    - run: rm -f $HOME/.cargo/config
      shell: bash
